export const EXTENSION_ENABLE = "EXTENSION_ENABLE"
export const EXTENSION_VISIBLE = "EXTENSION_VISIBLE"
export const EXTENSION_LOGGED_IN = "EXTENSION_LOGGED_IN"
export const AUTH_STATE = "AUTH_STATE"
